import ROOT
import math

plot_options =  {

    "parton_hadV_pt":                {'binning':[50,500,2000], 'tex':'p_{T}(had V)'},
    "parton_hadV_eta":               {'binning':[50,-3,3], 'tex':'#eta(had V)'},
    "parton_hadV_mass":              {'binning':[50,50,150], 'tex':'M(had V)'},

    "parton_hadV_angle_theta":             {'binning':[50,0,math.pi], 'tex':'#theta'},
    "parton_hadV_angle_Theta":             {'binning':[50,0,math.pi], 'tex':'#Theta'},
    "parton_hadV_angle_phi":               {'binning':[50,-math.pi,math.pi], 'tex':'#phi'},

    "parton_hadV_q1_pt":             {'binning':[50,500,2000], 'tex':'p_{T}(q_{1})'},
    "parton_hadV_q1_eta":            {'binning':[50,-5,5], 'tex':'#eta(q_{1})'},
    "parton_hadV_q1_mass":           {'binning':[50,0,10], 'tex':'M(q_{1})'},
    "parton_hadV_q1_pdgId":          {'binning':[12,-6,6], 'tex':'pdgId(q_{1})'},

    "parton_hadV_q2_pt":             {'binning':[50,500,2000], 'tex':'p_{T}(q_{2})'},
    "parton_hadV_q2_eta":            {'binning':[50,-5,5], 'tex':'#eta(q_{2})'},
    "parton_hadV_q2_mass":           {'binning':[50,0,10], 'tex':'M(q_{2})'},
    "parton_hadV_q2_pdgId":          {'binning':[12,-6,6], 'tex':'pdgId(q_{2})'},

    "parton_lepV_pt":                {'binning':[50,500,2000], 'tex':'p_{T}(lep V)'},
    "parton_lepV_eta":               {'binning':[50,-5,5], 'tex':'#eta(lep V)'},
    "parton_lepV_mass":              {'binning':[50,50,150], 'tex':'M(lep V)'},

    "parton_lepV_l1_pt":            {'binning':[50,500,2000], 'tex':'p_{T}(l_{1})'},
    "parton_lepV_l1_eta":           {'binning':[50,-5,5], 'tex':'#eta(l_{1})'},
    "parton_lepV_l1_phi":           {'binning':[50,0,10], 'tex':'M(l_{1})'},
    "parton_lepV_l1_pdgId":         {'binning':[12,-6,6], 'tex':'pdgId(l_{1})'},

    "parton_lepV_l2_pt":            {'binning':[50,500,2000], 'tex':'p_{T}(l_{2})'},
    "parton_lepV_l2_eta":           {'binning':[50,-5,5], 'tex':'#eta(l_{2})'},
    "parton_lepV_l2_phi":           {'binning':[50,0,10], 'tex':'M(l_{2})'},
    "parton_lepV_l2_pdgId":         {'binning':[12,-6,6], 'tex':'pdgId(l_{2})'},

    "delphesJet_dR_matched_hadV_parton": {'binning':[50,0,.5], 'tex':'#Delta R(jet, had V)'},
    "delphesJet_dR_lepV_parton":         {'binning':[50,0,.5], 'tex':'#Delta R(jet, lep V)'},
    "delphesJet_dR_hadV_q1":             {'binning':[50,0,.5], 'tex':'#Delta R(jet, q_{1})'},
    "delphesJet_dR_hadV_q2":             {'binning':[50,0,.5], 'tex':'#Delta R(jet, q_{2})'},
    "delphesJet_dR_hadV_maxq1q2":        {'binning':[50,0,.5], 'tex':'max #Delta R(jet, q_{1,2})'},

    "delphesJet_pt"                 :{'binning':[50,0,2000], 'tex':'p_{T}(jet)'},
    "delphesJet_eta"                :{'binning':[50,-5,5], 'tex':'#eta(jet)'},
    "delphesJet_mass"               :{'binning':[50,50,120], 'tex':'M(jet) unpruned'},
    "delphesJet_nConstituents"      :{'binning':[50,0,100], 'tex':'n-constituents'},
    "delphesJet_SDmass"             :{'binning':[50,50,120], 'tex':'M_{SD}(jet)'},
    "delphesJet_SDsubjet0_deltaEta" :{'binning':[50,-0.6,0.6], 'tex':'#Delta#eta(jet,jet_{SD,0})'},
    "delphesJet_SDsubjet0_deltaPhi" :{'binning':[50,-0.6,0.6], 'tex':'#Delta#phi(jet,jet_{SD,0})'},
    "delphesJet_SDsubjet0_deltaR"   :{'binning':[50,0,0.7], 'tex':'#Delta R(jet,jet_{SD,0})'},
    "delphesJet_SDsubjet0_mass"     :{'binning':[50,0,100], 'tex':'M_{SD}(jet_{0})'},
    "delphesJet_SDsubjet1_deltaEta" :{'binning':[50,-0.6,0.6], 'tex':'#Delta#eta(jet,jet_{SD,1})'},
    "delphesJet_SDsubjet1_deltaPhi" :{'binning':[50,-0.6,0.6], 'tex':'#Delta#phi(jet,jet_{SD,1})'},
    "delphesJet_SDsubjet1_deltaR"   :{'binning':[50,0,0.7], 'tex':'#Delta R(jet,jet_{SD,1})'},
    "delphesJet_SDsubjet1_mass"     :{'binning':[50,0,100], 'tex':'M_{SD}(jet_{1})'},
    "delphesJet_tau1"               :{'binning':[50,0,.5], 'tex':'#tau_{1}'},
    "delphesJet_tau2"               :{'binning':[50,0,.15],'tex':'#tau_{2}'},
    "delphesJet_tau3"               :{'binning':[50,0,.15],'tex':'#tau_{3}'},
    "delphesJet_tau4"               :{'binning':[50,0,.15],'tex':'#tau_{4}'},
    "delphesJet_tau21"              :{'binning':[50,0,1], 'tex':'#tau_{21}'},
    "delphesJet_tau32"              :{'binning':[50,0,1], 'tex':'#tau_{32}'},
#https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/RecoJets/JetProducers/python/ECF_cff.py
    "delphesJet_ecf1"               :{'binning':[50,0,2000], 'tex':"ecf1"},
    "delphesJet_ecf2"               :{'binning':[50,0,100000], 'tex':"ecf2"},
    "delphesJet_ecf3"               :{'binning':[50,0,1000000], 'tex':"ecf3"},
    "delphesJet_ecfC1"              :{'binning':[50,0,.5], 'tex':"ecfC1"},
    "delphesJet_ecfC2"              :{'binning':[50,0,.5], 'tex':"ecfC2"},
    "delphesJet_ecfC3"              :{'binning':[50,0,.5], 'tex':"ecfC3"},
    "delphesJet_ecfD"               :{'binning':[50,0,8], 'tex':"ecfD"},
    "delphesJet_ecfDbeta2"          :{'binning':[50,0,20], 'tex':"ecfDbeta2"},
    "delphesJet_ecfM1"              :{'binning':[50,0,0.35], 'tex':"ecfM1"},
    "delphesJet_ecfM2"              :{'binning':[50,0,0.2], 'tex':"ecfM2"},
    "delphesJet_ecfM3"              :{'binning':[50,0,0.2], 'tex':"ecfM3"},
    "delphesJet_ecfM1beta2"         :{'binning':[50,0,0.35], 'tex':"ecfM1beta2"},
    "delphesJet_ecfM2beta2"         :{'binning':[50,0,0.2], 'tex':"ecfM2beta2"},
    "delphesJet_ecfM3beta2"         :{'binning':[50,0,0.2], 'tex':"ecfM3beta2"},
    "delphesJet_ecfN1"              :{'binning':[50,0,0.2], 'tex':"ecfN1"},
    "delphesJet_ecfN2"              :{'binning':[50,0,0.5], 'tex':"ecfN2"},
    "delphesJet_ecfN3"              :{'binning':[50,0,5], 'tex':"ecfN3"},
    "delphesJet_ecfN1beta2"         :{'binning':[50,0,0.1], 'tex':"ecfN1beta2"},
    "delphesJet_ecfN2beta2"         :{'binning':[50,0,0.5], 'tex':"ecfN2beta2"},
    "delphesJet_ecfN3beta2"         :{'binning':[50,0,5], 'tex':"ecfN3beta2"},
    "delphesJet_ecfU1"              :{'binning':[50,0,0.5], 'tex':"ecfU1"},
    "delphesJet_ecfU2"              :{'binning':[50,0,0.04], 'tex':"ecfU2"},
    "delphesJet_ecfU3"              :{'binning':[50,0,0.004], 'tex':"ecfU3"},
    "delphesJet_ecfU1beta2"         :{'binning':[50,0,0.2], 'tex':"ecfU1beta2"},
    "delphesJet_ecfU2beta2"         :{'binning':[50,0,0.01], 'tex':"ecfU2beta2"},
    "delphesJet_ecfU3beta2"         :{'binning':[50,0,0.001], 'tex':"ecfU3beta2"},
}
